version: '3'
services:

# docker exec -it fasterthanflaskarticle_dvdrental_1 bash

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
        - /var/lib/postgres
    environment:
        POSTGRES_DB: dvdrental
        POSTGRES_USER: dvdrental
        POSTGRES_PASSWORD: dvdrental

  # blog:
  #   build: .
  #   links:
  #     - blogdb
  #   ports:
  #     - "8888:8888"
